#include <gtk/gtk.h>
#include "resources.h"

static const char *css_data =
"window.background {"
"   background-color: #121212;"
"   color: #eeeeee;"
"}"
"box, stack, grid {"
"   background-color: transparent;"
"}"
"label {"
"   background-color: transparent;"
"   background-image: none;"
"   color: #eeeeee;"
"   font-size: 18px;"
"}"
"button {"
"   background-image: none;"
"   background-color: #2c2c2c;"
"   color: #ffffff;"
"   border-radius: 8px;"
"   padding: 10px;"
"   border: 2px solid #3c3c3c;"
"   box-shadow: none;"
"}"
"button:hover {"
"   background-color: #444444;"
"}"
"button:disabled {"
"   background-color: #161616;"
"   color: #444444;"
"   border-color: #1a1a1a;"
"}"
"button.num-btn {"
"   transition: background-color 200ms ease-out,"
"               border-color 200ms ease-out,"
"               color 200ms ease-out,"
"               opacity 200ms ease-out;"
"}"
"button.num-btn.domino-out,"
"button.num-btn.domino-out:disabled {"
"   background-color: #161616;"
"   border-color: #1a1a1a;"
"   color: #3a3a3a;"
"   opacity: 0.4;"
"}"
"window.no-anim button.num-btn {"
"   transition: none;"
"}"
"combobox button {"
"   padding: 5px 10px;"
"}"
"menu {"
"   background-color: #2c2c2c;"
"   color: #ffffff;"
"   border: 2px solid #3c3c3c;"
"}"
"menuitem {"
"   padding: 8px;"
"}"
"menuitem:hover {"
"   background-color: #444444;"
"}"
".title {"
"   font-size: 32px;"
"   font-weight: bold;"
"}"
".info {"
"   font-size: 20px;"
"   color: #00ffaa;"
"}"
".danger {"
"   font-size: 28px;"
"   color: #ff5555;"
"}"
".copyright {"
"   font-size: 12px;"
"   color: #888888;"
"}"
"window.light {"
"   background-color: #f0f0f0;"
"   color: #222222;"
"}"
"window.light label {"
"   background-color: transparent;"
"   background-image: none;"
"   color: #222222;"
"}"
"window.light button {"
"   background-image: none;"
"   background-color: #ffffff;"
"   color: #222222;"
"   border: 1px solid #cccccc;"
"}"
"window.light button:hover {"
"   background-color: #e0e0e0;"
"}"
"window.light button:disabled {"
"   background-color: #e8e8e8;"
"   color: #999999;"
"   border-color: #d0d0d0;"
"}"
"window.light button.num-btn.domino-out,"
"window.light button.num-btn.domino-out:disabled {"
"   background-color: #ececec;"
"   border-color: #d8d8d8;"
"   color: #b5b5b5;"
"   opacity: 0.6;"
"}"
"window.light menu {"
"   background-color: #ffffff;"
"   color: #222222;"
"   border: 1px solid #cccccc;"
"}"
"window.light menuitem:hover {"
"   background-color: #e0e0e0;"
"}"
"window.light .title {"
"   color: #111111;"
"}"
"window.light .info {"
"   color: #00aa55;"
"}"
"window.light .danger {"
"   color: #cc0000;"
"}"
"window.light .copyright {"
"   color: #666666;"
"}";

void resources_load_css() {
    GtkCssProvider *provider = gtk_css_provider_new();
    gtk_css_provider_load_from_data(provider, css_data, -1, NULL);
    gtk_style_context_add_provider_for_screen(
        gdk_screen_get_default(),
        GTK_STYLE_PROVIDER(provider),
        GTK_STYLE_PROVIDER_PRIORITY_APPLICATION
    );
    g_object_unref(provider);
}
